Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,31 +13,54 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
-    - name: Build the Docker image
-      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
+      -
+        name: Checkout
+        uses: actions/checkout@v4
+      -
+        name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ vars.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+      -
+        name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+      -
+        name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+      -
+        name: Build and push
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          push: true
+          tags: user/app:latest
+   # steps:
+   # - uses: actions/checkout@v4
+   # - name: Build the Docker image
+   #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
 
-    - name: Create docker Network
-      run: docker network create network1
+    #- name: Create docker Network
+     # run: docker network create network1
 
-    - name : Run MONGO container
-      run:  docker run --network=network1 --name mongo -d -p 27017:27017 mongo
+    #- name : Run MONGO container
+     # run:  docker run --network=network1 --name mongo -d -p 27017:27017 mongo
 
-    - name : Run Backend container
-      run: docker run --network=network1 --name backend -d -p 3000:3000 sidraut007/movie-back
+    #- name : Run Backend container
+     # run: docker run --network=network1 --name backend -d -p 3000:3000 sidraut007/movie-back
 
-    - name: Run Application container
-      run: docker run --network=network1 --name frontend -d -p 5173:5173 sidraut007/movie-front
+    #- name: Run Application container
+     # run: docker run --network=network1 --name frontend -d -p 5173:5173 sidraut007/movie-front
 
-    - name: List running containers
-      run: docker ps -a
+   # - name: List running containers
+    #  run: docker ps -a
 
-    - name: Cleanup all containers
-      run: docker rm -f $(docker ps -aq) || true
+    #- name: Cleanup all containers
+     # run: docker rm -f $(docker ps -aq) || true
 
-  
-    - name: Using docker-compose deployment
-      run:  docker compose up -d
+#- name: Using docker-compose deployment
+ #     run:  docker compose up -d
+
 
     
       
